"""`mfc gen-nutrition-doc` — generate docs/NUTRITION_FIELDS.md from the nutrient map."""

from __future__ import annotations

import argparse
import csv

from ..core import log
from ..core.config import Config
from ..ops.usda_nutrient_map import NUTRIENT_MAP


def register(subparsers: argparse._SubParsersAction) -> None:
    p = subparsers.add_parser("gen-nutrition-doc", help="Regenerate docs/NUTRITION_FIELDS.md from the map + USDA dump")
    p.set_defaults(handler=run)


def run(args: argparse.Namespace, config: Config) -> int:
    nut_csv = config.repo_root / "data" / "usda" / "nutrient.csv"
    units: dict[int, tuple[str, str]] = {}
    with open(nut_csv) as f:
        for r in csv.DictReader(f):
            units[int(r["id"])] = (r["name"], r["unit_name"].lower())

    by_col: dict[str, list[tuple[int, str, str]]] = {}
    for nid, col in NUTRIENT_MAP.items():
        name, unit = units.get(nid, ("?", "?"))
        by_col.setdefault(col, []).append((nid, name, unit))

    lines = [
        "# Nutrition fields reference",
        "",
        "Generated by `mfc gen-nutrition-doc`. Every column on `ingredient_details` is listed below with its unit + the USDA `nutrient_id`(s) it draws from.",
        "",
        "| Column | Unit | USDA nutrient_id(s) | USDA name(s) |",
        "|---|---|---|---|",
    ]
    for col in sorted(by_col):
        entries = by_col[col]
        ids = " / ".join(str(n) for n, _, _ in entries)
        names = " / ".join(n for _, n, _ in entries)
        unit = entries[0][2]
        lines.append(f"| `{col}` | {unit} | {ids} | {names} |")

    out = config.repo_root / "docs" / "NUTRITION_FIELDS.md"
    out.write_text("\n".join(lines) + "\n")
    log.ok(f"wrote {out}")
    return 0
